input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["trades.crudo"]
    codec => "json"
    client_id => "logstash-nrt-trades"
    group_id => "logstash-grupo-cripto"
  }
}

filter {
  # Solo procesa si trae el discriminante del contrato de datos
  if [tipo_fuente] {
    date {
      match => ["ts_evento", "ISO8601"]
      target => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cripto-%{[tipo_fuente]}-%{+YYYY.MM.dd}"
  }
  # Habilitado temporalmente para que veas los datos fluir en la consola
  stdout { codec => rubydebug }
}